# Generated by Django 2.2.6 on 2019-11-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('middlename', models.CharField(max_length=500)),
                ('aboutme', models.CharField(max_length=500)),
                ('inputDate', models.IntegerField(default=0, null=True)),
                ('number', models.CharField(max_length=500)),
                ('release', models.CharField(max_length=500)),
                ('serial', models.CharField(max_length=500)),
                ('specialty', models.CharField(max_length=500)),
                ('surname', models.CharField(max_length=500)),
                ('who', models.CharField(max_length=500)),
                ('whyme', models.CharField(max_length=500)),
            ],
        ),
    ]
