# Generated by Django 2.2.6 on 2019-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='inputDate',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
