# Generated by Django 2.2.6 on 2020-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackweb', '0002_auto_20191119_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('inn', models.CharField(max_length=500)),
                ('fio', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=500)),
                ('telephon', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('task1', models.CharField(max_length=500)),
                ('task2', models.CharField(max_length=500)),
                ('task3', models.CharField(max_length=500)),
                ('task4', models.CharField(max_length=500)),
                ('task5', models.CharField(max_length=500)),
            ],
        ),
    ]
