# Generated by Django 2.2.6 on 2019-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20191105_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='count2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='countZ',
            field=models.IntegerField(null=True),
        ),
    ]
