# Generated by Django 2.2.6 on 2019-11-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0004_auto_20191105_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('hour', models.IntegerField(null=True)),
                ('minute', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('au92', models.IntegerField(null=True)),
                ('au95', models.IntegerField(null=True)),
                ('au100', models.IntegerField(null=True)),
                ('eda', models.IntegerField(null=True)),
                ('napit', models.IntegerField(null=True)),
                ('soput', models.IntegerField(null=True)),
                ('sigarets', models.IntegerField(null=True)),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.AZS')),
            ],
        ),
    ]
